name: CI
on:
  pull_request:
  push:
    branches:
    - master
    - dev
    - ci

  workflow_run:
    workflows:
    - sync-channels
    types:
    - completed
    branches:
    - master

jobs:
  test-rust:
    name: Test Rust
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        channel: [nightly]
        profile: [default]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Prepare nix-shell and Rust crates
      run: |
        cd examples/hello-world
        nix-shell --pure \
          --argstr profile ${{ matrix.profile }} \
          --argstr channel ${{ matrix.channel }} \
          --command "unset SSL_CERT_FILE; cargo metadata --format-version=1 >/dev/null"

    - name: Test cargo clippy
      if: matrix.profile == 'default'
      run: |
        cd examples/hello-world
        set -o pipefail
        ls -l ~/.cargo || true
        ls -l ~/.cargo/bin || true
        rm -rf ~/.cargo/bin
        nix-shell --pure \
          --argstr profile ${{ matrix.profile }} \
          --argstr channel ${{ matrix.channel }} \
          --command "type cc rustc cargo cargo-clippy clippy-driver; env RUSTFLAGS=-Zprint-link-args cargo clippy -- --cap-lints=warn" 2>&1 | tee out || true
        nix-shell -p patchelf --command 'patchelf --print-rpath target/debug/deps/libthiserror_impl-*.so'
        [[ "$(< out)" == *"warning: this loop never actually loops"* ]]
        rm -rf target
